### ISSUE TITLE
Trigger generating org.neo4j.graphdb.NotInTransactionException: This transaction has already been closed

### ISSUE THREAD

**Issue by dimitriwoei** [neo4j/apoc#411]
Hi,

I'm getting the following error:

Error executing trigger myTrigger in phase afterAsync
org.neo4j.graphdb.QueryExecutionException: Failed to invoke function apoc.convert.toJson: Caused by: org.neo4j.graphdb.NotInTransactionException: This transaction has already been closed

The code for the trigger is:

"CALL apoc.load.jsonParams(
"http://localhost:8082/topics/neodb-cdc",
{
method: "POST",
Content-Type: "application/vnd.kafka.json.v2+json",
Accept: "application/vnd.kafka.v2+json"
},
apoc.convert.toJson({records:[{key: "neo4j_update", value: {
createdNodes: $createdNodes,
deletedNodes: $deletedNodes,
createdRelationships: $createdRelationships,
deletedRelationships: $deletedRelationships,
removedLabels: $removedLabels,
removedNodeProperties: $removedNodeProperties,
removedRelationshipProperties: $removedRelationshipProperties,
assignedLabels: $assignedLabels,
assignedNodeProperties: $assignedNodeProperties,
assignedRelationshipProperties: $assignedRelationshipProperties
}
}]})
) YIELD value
RETURN value"

Sometimes the trigger runs without generating errors (I can see that the call to localhost:8082 has been succesful), sometimes it doesn't. It seems quite random. 

## Expected Behavior (Mandatory)
Execution of the trigger without error

## Actual Behavior (Mandatory)
2023-05-16 13:12:42.166+0000 WARN  [a.t.TriggerHandler] [neo4j/a139b05b] Error executing trigger myTrigger in phase afterAsync
org.neo4j.graphdb.QueryExecutionException: Failed to invoke function `apoc.convert.toJson`: Caused by: org.neo4j.graphdb.NotInTransactionException: The transaction has been closed.
        at org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(QueryExecutionKernelException.java:35) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.converted(ResultSubscriber.java:426) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.assertNoErrors(ResultSubscriber.java:407) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchResults(ResultSubscriber.java:363) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.nextFromSubscriber(ResultSubscriber.java:330) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchNextOrNull(ResultSubscriber.java:301) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchNextOrNull(ResultSubscriber.java:58) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.internal.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60) ~[neo4j-collections-4.4.8.jar:4.4.8]
        at org.neo4j.internal.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46) ~[neo4j-collections-4.4.8.jar:4.4.8]
        at org.neo4j.internal.helpers.collection.Iterators.count(Iterators.java:383) ~[neo4j-collections-4.4.8.jar:4.4.8]
        at org.neo4j.internal.helpers.collection.Iterators.count(Iterators.java:369) ~[neo4j-collections-4.4.8.jar:4.4.8]
        at apoc.trigger.TriggerHandler.lambda$executeTriggers$14(TriggerHandler.java:267) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at apoc.trigger.TriggerHandler.executeTriggers(TriggerHandler.java:257) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.trigger.TriggerHandler.lambda$afterAsync$11(TriggerHandler.java:229) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.util.Util.retryInTx(Util.java:217) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.util.Util.lambda$inTxFuture$4(Util.java:241) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.neo4j.kernel.impl.query.QueryExecutionKernelException: Failed to invoke function `apoc.convert.toJson`: Caused by: org.neo4j.graphdb.NotInTransactionException: The transaction has been closed.
        ... 20 more
Caused by: org.neo4j.exceptions.CypherExecutionException: Failed to invoke function `apoc.convert.toJson`: Caused by: org.neo4j.graphdb.NotInTransactionException: The transaction has been closed.
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingReadQueryContext.callFunction(ExceptionTranslatingQueryContext.scala:237) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.UserFunctionInvocation.call(FunctionInvocation.scala:58) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.FunctionInvocation.apply(FunctionInvocation.scala:42) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.CoerceTo.apply(CoerceTo.scala:31) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$2(ProcedureCallPipe.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at scala.collection.immutable.List.map(List.scala:297) ~[scala-library-2.12.13.jar:?]
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$1(ProcedureCallPipe.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.nextCur(ClosingIterator.scala:107) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.innerHasNext(ClosingIterator.scala:113) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchResults(ResultSubscriber.java:362) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        ... 17 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Failed to invoke function `apoc.convert.toJson`: Caused by: org.neo4j.graphdb.NotInTransactionException: The transaction has been closed.
        at org.neo4j.procedure.impl.ProcedureCompilation.rethrowProcedureException(ProcedureCompilation.java:534) ~[neo4j-procedure-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.proc.GeneratedFunction_toJson3893895974330232.apply(Unknown Source) ~[?:?]
        at org.neo4j.procedure.impl.ProcedureRegistry.callFunction(ProcedureRegistry.java:250) ~[neo4j-procedure-4.4.8.jar:4.4.8]
        at org.neo4j.procedure.impl.GlobalProceduresRegistry.callFunction(GlobalProceduresRegistry.java:358) ~[neo4j-procedure-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.callFunction(AllStoreHolder.java:1139) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.functionCall(AllStoreHolder.java:1031) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callFunction(CallSupport.scala:38) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.callFunction(TransactionBoundQueryContext.scala:1150) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingReadQueryContext.callFunction(ExceptionTranslatingQueryContext.scala:237) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.UserFunctionInvocation.call(FunctionInvocation.scala:58) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.FunctionInvocation.apply(FunctionInvocation.scala:42) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.CoerceTo.apply(CoerceTo.scala:31) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$2(ProcedureCallPipe.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at scala.collection.immutable.List.map(List.scala:297) ~[scala-library-2.12.13.jar:?]
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$1(ProcedureCallPipe.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.nextCur(ClosingIterator.scala:107) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.innerHasNext(ClosingIterator.scala:113) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchResults(ResultSubscriber.java:362) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        ... 17 more
Caused by: org.neo4j.graphdb.NotInTransactionException: The transaction has been closed.
        at org.neo4j.kernel.impl.coreapi.TransactionImpl.checkInTransaction(TransactionImpl.java:879) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.coreapi.TransactionImpl.kernelTransaction(TransactionImpl.java:740) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.core.NodeEntity.getLabels(NodeEntity.java:611) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at apoc.convert.Json.nodeToMap(Json.java:68) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.convert.Json.relToMap(Json.java:57) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.convert.Json.writeJsonResult(Json.java:34) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at apoc.convert.Json.writeJsonResult(Json.java:40) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.convert.Json.lambda$writeJsonResult$1(Json.java:45) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:589) ~[?:?]
        at apoc.convert.Json.writeJsonResult(Json.java:44) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.convert.Json.lambda$writeJsonResult$1(Json.java:45) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:589) ~[?:?]
        at apoc.convert.Json.writeJsonResult(Json.java:44) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at apoc.convert.Json.writeJsonResult(Json.java:40) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.convert.Json.lambda$writeJsonResult$1(Json.java:45) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at java.util.stream.ReduceOps$4ReducingSink.accept(ReduceOps.java:220) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:589) ~[?:?]
        at apoc.convert.Json.writeJsonResult(Json.java:44) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at apoc.convert.Json.toJson(Json.java:93) ~[apoc-4.4.0.8.jar:4.4.0.8]
        at org.neo4j.kernel.impl.proc.GeneratedFunction_toJson3893895974330232.apply(Unknown Source) ~[?:?]
        at org.neo4j.procedure.impl.ProcedureRegistry.callFunction(ProcedureRegistry.java:250) ~[neo4j-procedure-4.4.8.jar:4.4.8]
        at org.neo4j.procedure.impl.GlobalProceduresRegistry.callFunction(GlobalProceduresRegistry.java:358) ~[neo4j-procedure-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.callFunction(AllStoreHolder.java:1139) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.kernel.impl.newapi.AllStoreHolder.functionCall(AllStoreHolder.java:1031) ~[neo4j-kernel-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callFunction(CallSupport.scala:38) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundReadQueryContext.callFunction(TransactionBoundQueryContext.scala:1150) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.planning.ExceptionTranslatingReadQueryContext.callFunction(ExceptionTranslatingQueryContext.scala:237) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.UserFunctionInvocation.call(FunctionInvocation.scala:58) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.FunctionInvocation.apply(FunctionInvocation.scala:42) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.CoerceTo.apply(CoerceTo.scala:31) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$2(ProcedureCallPipe.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at scala.collection.immutable.List.map(List.scala:297) ~[scala-library-2.12.13.jar:?]
        at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.$anonfun$internalCreateResultsByAppending$1(ProcedureCallPipe.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.nextCur(ClosingIterator.scala:107) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.innerHasNext(ClosingIterator.scala:113) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        at org.neo4j.cypher.internal.javacompat.ResultSubscriber.fetchResults(ResultSubscriber.java:362) ~[neo4j-cypher-4.4.8.jar:4.4.8]
        ... 17 more

## How to Reproduce the Problem

use apoc.refactor.cloneNodes or apoc.refactor.cloneSubGraph including relationships of a medium sized graph.

## Specifications (Mandatory)

Currently used versions

### Versions
Neo4j Docker image:  neo4j:4.4.8-community
APOC version: 4.4.0.8

**Comment by Lojjs** [comment]
@dimitriwoei Thanks for reporting! We will investigate and come back to you

Best regards Louise, Neo4j Cypher Surface team

**Comment by dimitriwoei** [comment]
Hi,

I'm getting this error more consistently when removing relationships. Hope this helps.

**Comment by gem-neo4j** [comment]
Hi!

I found a bug in the way that deleted relationships were referencing their start and end nodes which gave me this error, I have now fixed this and it will be released in the next release (2025.03.0) :)  https://github.com/neo4j/apoc/pull/746
